### ISSUE TITLE
applywarp to elec_bin

### ISSUE THREAD

**Issue by HughWXY** [HughWXY/ntools_elec#3]
With FSL 6.0, applywarp to electrode mask will give an empty image. However if binarize the mask first, then applywarp works fine. 

This seems only reproducible under FSL 6.0

**Comment by jingyunc** [comment]
But won't the elec mask lose its intensity (i.e. label) values after being binarized?

**Comment by HughWXY** [comment]
> But won't the elec mask lose its intensity (i.e. label) values after being binarized?

true, but at least we know binary mask works.

**Comment by jingyunc** [comment]
I found a potential solution: first convert elec_bin to integer data type with mri_convert -odt int, then applywarp on the converted elec_bin. This seemed to fix FSL6's misreading of elec_bin, and produce correct warped elec_bin.

**Comment by HughWXY** [comment]
bug fix in saving nifti: change bitpix to 32, corresponding to datatype 8.
